kind: Service
apiVersion: v1
metadata:
  name: demo-metrics-public
  labels:
    app: demo-metrics
spec:
  type: LoadBalancer
  selector:
    app: demo-metrics
  ports:
    - port: 8080
      targetPort: 8080
      name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: demo-metrics
  labels:
    app: demo-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-metrics
  template:
    metadata:
      labels:
        app: demo-metrics
        version: v1
    spec:
      containers:
        - name: demo-metrics
          image: tuxtor/demo-metrics
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: demo-metrics-servicemonitor
  labels:
    app: demo-metrics
spec:
  selector:
    matchLabels:
      app: demo-metrics
  namespaceSelector:
    any: true
  endpoints:
    - port: http

