kind: Service
apiVersion: v1
metadata:
  name: demo-jvm-languages
  labels:
    app: demo-jvm-languages
spec:
  type: NodePort
  selector:
    app: demo-jvm-languages
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: demo-jvm-languages
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-jvm-languages
  template:
    metadata:
      labels:
        app: demo-jvm-languages
        version: v1
    spec:
      containers:
      - name: demo-jvm-languages
        image: tuxtor/demo-jvm-languages
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
