apiVersion: v1
kind: Service
metadata:
  name: zipkin-public
spec:
  type: LoadBalancer
  selector:
    app: zipkin
  ports:
    - port: 80
      targetPort: 9411
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
spec:
  ports:
    - port: 9411
      protocol: TCP
  selector:
    app: zipkin
---
kind: Pod
apiVersion: v1
metadata:
  name: zipkin
  labels:
    app: zipkin
spec:
  containers:
    - name: zipkin
      image: openzipkin/zipkin
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 9411
